name: foxyn_bot
description: Discord bot handling registration and whitelisting for the Foxyn minecraft server.
version: 0.0.1
homepage: https://foxyn.net

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  crypto: ^3.0.1
  gsheets: ^0.3.1
  mailer: ^5.0.2
  nyxx: ^2.0.0-rc.13
  path: ^1.8.0
